/**
 * Generated by react-native-coverage CocoaPods helper.
 * Do not edit by hand — regenerate via apply_post_install! /
 * Expo config plugin `frameworkNamePrefixes`.
 */
#pragma once

#ifndef COVERAGE_ENABLED
#define COVERAGE_ENABLED 1
#endif

#ifndef COVERAGE_PROFILE_FILE_PATTERN
#define COVERAGE_PROFILE_FILE_PATTERN "coverage-%m.profraw"
#endif

#ifndef COVERAGE_FRAMEWORK_PREFIX_COUNT
#define COVERAGE_FRAMEWORK_PREFIX_COUNT 1
static const char *const COVERAGE_FRAMEWORK_PREFIXES[] = {
  "CoverageFixture"
};
#endif
