# frozen_string_literal: true

# react-native-coverage CocoaPods helper (safe split).
#
# Expo / config plugin owns Android + stable iOS app-target mods.
# Pod LLVM coverage flags (and optional dynamic-framework restore) live here:
#
#   require_relative '../node_modules/react-native-coverage/cocoapods/coverage_post_install'
#   # After use_expo_modules! — wrap Installer so restore runs after Expo's staticlib downgrade:
#   ReactNativeCoverage.install_installer_hooks!
#
#   post_install do |installer|
#     ReactNativeCoverage.apply_post_install!(
#       installer,
#       framework_name_prefixes: ['CoverageFixture'],
#       force_dynamic_frameworks: true
#     )
#   end

require 'fileutils'

module ReactNativeCoverage
  module_function

  DEFAULT_FRAMEWORK_PREFIXES = ['CoverageFixture'].freeze
  COVERAGE_POD_NAMES = %w[Coverage CoverageFixture].freeze

  # Wrap Installer AFTER Expo's `use_expo_modules!` patch. Call from the Podfile
  # below `use_expo_modules!` (Expo plugin injects the call).
  # Using prepend-at-require races Expo's define_method and recurses forever.
  def install_installer_hooks!(options = {})
    if options.key?(:force_dynamic_frameworks)
      self.force_dynamic_frameworks = options[:force_dynamic_frameworks]
    end
    return if @installer_hooks_installed

    installer_class = Pod::Installer
    original = installer_class.instance_method(:run_podfile_pre_install_hooks)

    installer_class.define_method(:run_podfile_pre_install_hooks) do
      original.bind_call(self)
      ReactNativeCoverage.restore_dynamic_frameworks!(self)
    end

    @installer_hooks_installed = true
  end

  def restore_dynamic_frameworks!(installer, pod_names: nil)
    return unless force_dynamic_frameworks_enabled?

    names = Array(pod_names || dynamic_framework_pod_names)
    restored = []

    installer.pod_targets.each do |target|
      next unless names.any? { |name| target.name == name || target.name.include?(name) }

      target.define_singleton_method(:build_type) do
        Pod::BuildType.dynamic_framework
      end
      restored << target.name
    end

    return if restored.empty?

    Pod::UI.puts '[react-native-coverage] Restored dynamic frameworks for: ' \
                 "#{restored.uniq.join(', ')}".green
  end

  def force_dynamic_frameworks_enabled?
    # Default false: Expo force-statics React-Core, so dynamic Coverage* pods
    # fail CocoaPods transitive static→dynamic validation. Opt in on bare/RNFB.
    @force_dynamic_frameworks == true
  end

  def force_dynamic_frameworks=(value)
    @force_dynamic_frameworks = value
  end

  def dynamic_framework_pod_names
    @dynamic_framework_pod_names || COVERAGE_POD_NAMES
  end

  def dynamic_framework_pod_names=(names)
    @dynamic_framework_pod_names = Array(names)
  end

  def apply_ios_native_coverage!(build_settings, link_profile:)
    build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'YES'
    build_settings['OTHER_CFLAGS'] =
      '$(inherited) -fprofile-instr-generate -fcoverage-mapping'
    build_settings['OTHER_SWIFT_FLAGS'] =
      '$(inherited) -profile-generate -profile-coverage-mapping'
    return unless link_profile

    # -Wl,-u keeps __llvm_profile_set_filename from being dead-stripped so
    # per-image flush can retarget coverage-%m.profraw under dynamic frameworks.
    build_settings['OTHER_LDFLAGS'] = [
      '$(inherited)',
      '-fprofile-instr-generate',
      '-Wl,-u,___llvm_profile_set_filename',
      '-L$(DT_TOOLCHAIN_DIR)/usr/lib/swift/$(PLATFORM_NAME)',
      '-L$(SDKROOT)/usr/lib/swift',
    ].join(' ')
  end

  def write_coverage_config_header!(prefixes:)
    header_path = File.expand_path('../ios/CoverageConfig.h', __dir__)
    list = Array(prefixes)
    list = DEFAULT_FRAMEWORK_PREFIXES if list.empty?

    entries = list.map { |prefix| "  \"#{prefix}\"" }.join(",\n")
    contents = <<~HEADER
      /**
       * Generated by react-native-coverage CocoaPods helper.
       * Do not edit by hand — regenerate via apply_post_install! /
       * Expo config plugin `frameworkNamePrefixes`.
       */
      #pragma once

      #ifndef COVERAGE_ENABLED
      #define COVERAGE_ENABLED 1
      #endif

      #ifndef COVERAGE_PROFILE_FILE_PATTERN
      #define COVERAGE_PROFILE_FILE_PATTERN "coverage-%m.profraw"
      #endif

      #ifndef COVERAGE_FRAMEWORK_PREFIX_COUNT
      #define COVERAGE_FRAMEWORK_PREFIX_COUNT #{list.length}
      static const char *const COVERAGE_FRAMEWORK_PREFIXES[] = {
      #{entries}
      };
      #endif
    HEADER

    FileUtils.mkdir_p(File.dirname(header_path))
    File.write(header_path, contents)
    Pod::UI.puts "[react-native-coverage] Wrote #{header_path} " \
                 "(prefixes=#{list.inspect})".green
  end

  def apply_post_install!(installer, options = {})
    prefixes = Array(options.fetch(:framework_name_prefixes, DEFAULT_FRAMEWORK_PREFIXES))
    link_profile = options.fetch(:link_profile, true)
    instrument_app = options.fetch(:instrument_app, true)
    quiet = options.fetch(:quiet, false)
    write_header = options.fetch(:write_config_header, true)
    force_dynamic = options.fetch(:force_dynamic_frameworks, false)

    self.force_dynamic_frameworks = force_dynamic
    self.dynamic_framework_pod_names =
      options.fetch(:dynamic_framework_pod_names, COVERAGE_POD_NAMES + prefixes)

    # Belt-and-suspenders: re-apply if Expo/other hooks ran after our prepend.
    restore_dynamic_frameworks!(installer) if force_dynamic

    write_coverage_config_header!(prefixes: prefixes) if write_header

    if instrument_app
      installer.aggregate_targets.each do |aggregate_target|
        user_project = aggregate_target.user_project
        next if user_project.nil?

        user_project.native_targets.each do |target|
          target.build_configurations.each do |config|
            apply_ios_native_coverage!(config.build_settings, link_profile: true)
          end
        end
        user_project.save
      end
    end

    installer.pods_project.targets.each do |target|
      matched = prefixes.any? { |prefix| target.name.include?(prefix) }
      # Always link profile into the Coverage flusher Pod under dynamic linkage
      # so configure/set_filename and the final pod write resolve.
      is_coverage_pod = target.name == 'Coverage'
      next unless matched || is_coverage_pod

      target.build_configurations.each do |config|
        apply_ios_native_coverage!(
          config.build_settings,
          link_profile: link_profile || is_coverage_pod
        )
      end
    end

    unless quiet
      Pod::UI.puts '[react-native-coverage] applied LLVM coverage flags ' \
                   "(prefixes=#{prefixes.inspect}, force_dynamic=#{force_dynamic})"
    end
  end
end

# Do not auto-install hooks on require — Expo patches Installer during
# `use_expo_modules!`. Call `ReactNativeCoverage.install_installer_hooks!`
# from the Podfile after that (Expo config plugin injects the call).
